[build]
# Use a faster linker and set default target
rustflags = ["-C", "linker=clang", "-C", "link-arg=-fuse-ld=mold"]

[target.'cfg(target_os = "linux")']
# Use the system allocator for better performance
rustflags = ["-C", "linker=clang", "-C", "link-args=-fuse-ld=mold", "-C", "force-frame-pointers=yes"]

[env]
# Enable incremental compilation for all profiles
CARGO_INCREMENTAL = "1"

[install]
# Prefer minimal versions for faster dependency resolution
prefer-dynamic = true
